name: "publish"

on:
  push:
    branches:
      - test_release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenSSL on Windows
        if: matrix.platform == 'windows-latest'
        run: |
          choco install openssl -y
          echo "C:\Program Files\OpenSSL-Win64\bin" | Out-File -Append -Encoding ASCII $env:GITHUB_PATH

      - name: Verify OpenSSL Installation
        if: matrix.platform == 'windows-latest'
        run: openssl version

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: install frontend dependencies
        run: npm install

      # WASM 타겟 추가
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      # Trunk 설치 (WASM 빌드를 위해 필요)
      - name: Install trunk
        run: cargo install trunk

      - name: Build project
        run: trunk build

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
